### 1. Ver todas las salas
GET http://localhost:8080/api/sala/all

### 2. Crear sala (host)
POST http://localhost:8080/api/sala/crear
Content-Type: application/json

{
  "hostNombre": "Cash"
}

### 3. Unirse con código
POST http://localhost:8080/api/sala/XXXXX/unirse
Content-Type: application/json

{
  "nombre": "Pedro"
}

### 4. Ver sala por código
GET http://localhost:8080/api/sala/getCodigo/XXXXX
